"""
report.py
Generates a PDF summary of a patient's visit history: parasitemia trend
chart, per-visit table, and the same "screening estimate, not a diagnosis"
disclaimers shown in the app -- so the report is honest on its own, even if
it gets printed and separated from the web app.
"""

import io

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage

TEAL = colors.HexColor("#1F6F6B")
CORAL = colors.HexColor("#C2483D")
INK = colors.HexColor("#12252B")
INK_SOFT = colors.HexColor("#4B5D5E")


def _trend_chart_image(visits: list) -> bytes:
    dates = [v["visit_date"] for v in visits]
    values = [v["parasitemia_pct"] for v in visits]
    lows = [v["ci_low"] for v in visits]
    highs = [v["ci_high"] for v in visits]

    fig, ax = plt.subplots(figsize=(6.2, 2.6), dpi=150)
    ax.plot(dates, values, marker="o", color="#1F6F6B", linewidth=2)
    ax.fill_between(range(len(dates)), lows, highs, color="#1F6F6B", alpha=0.12)
    ax.set_ylabel("Parasitemia %")
    ax.set_ylim(bottom=0)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    plt.xticks(rotation=30, ha="right", fontsize=8)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    plt.close(fig)
    buf.seek(0)
    return buf.getvalue()


def generate_patient_report(patient: dict, visits: list, trend_text: str, out_path: str):
    doc = SimpleDocTemplate(out_path, pagesize=letter, topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("TitleCustom", parent=styles["Title"], textColor=INK, fontSize=20)
    label_style = ParagraphStyle("LabelCustom", parent=styles["Normal"], textColor=INK_SOFT, fontSize=9, spaceAfter=14)
    heading_style = ParagraphStyle("HeadingCustom", parent=styles["Heading2"], textColor=INK, spaceBefore=16, spaceAfter=8)
    disclaimer_style = ParagraphStyle("Disclaimer", parent=styles["Normal"], textColor=INK_SOFT, fontSize=8.5, leading=12)
    trend_style = ParagraphStyle("Trend", parent=styles["Normal"], textColor=INK, fontSize=11, spaceAfter=10)

    story = []
    story.append(Paragraph("Cell Scope — Patient Report", title_style))
    story.append(Paragraph(f"Patient: {patient['name']}  |  Generated by an automated screening tool", label_style))

    if visits:
        story.append(Paragraph("Parasitemia Trend", heading_style))
        chart_bytes = _trend_chart_image(visits)
        story.append(RLImage(io.BytesIO(chart_bytes), width=6.2 * inch, height=2.6 * inch))
        story.append(Spacer(1, 6))
        story.append(Paragraph(f"<b>Latest trend read:</b> {trend_text}", trend_style))

        story.append(Paragraph("Visit History", heading_style))
        table_data = [["Date", "Cells Analyzed", "Parasitemia %", "95% CI", "Tier"]]
        for v in visits:
            table_data.append([
                v["visit_date"],
                f"{v['cells_analyzed']} ({v['cells_parasitized']} flagged)",
                f"{v['parasitemia_pct']}%",
                f"{v['ci_low']}\u2013{v['ci_high']}%",
                v["tier"],
            ])
        table = Table(table_data, colWidths=[1.0 * inch, 1.7 * inch, 1.1 * inch, 1.1 * inch, 1.6 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), TEAL),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D6DEDC")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F1F4F3")]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(table)

        # Prescribed Medicines & Clinical Remedies Section
        story.append(Paragraph("Clinical Remedies & Suggested Treatment Framework", heading_style))
        latest = visits[-1]
        pct = latest["parasitemia_pct"]
        if pct > 5.0:
            rx_text = "<b>High Parasitemia (>5%):</b> Immediate WHO-recommended Artemisinin-Based Combination Therapy (ACT). Recommended regimen: Oral Artemether-Lumefantrine (Coartem 80/480mg) 6-dose schedule or IV Artesunate under clinical supervision. Continuous fever management, IV hydration, and daily blood smear monitoring."
        elif pct > 0.0:
            rx_text = "<b>Moderate/Low Parasitemia (<5%):</b> Standard Oral Artemether-Lumefantrine (Coartem 20/120mg) 6-dose course over 3 days. Supportive therapy: Paracetamol 500mg as needed for pyrexia, oral fluid rehydration, and follow-up thick/thin smear in 48-72 hours."
        else:
            rx_text = "<b>Uninfected (0% Parasites Detected):</b> No antimalarial chemotherapy indicated. Symptomatic management for non-malarial pyrexia as needed."
        
        rx_style = ParagraphStyle("RxCustom", parent=styles["Normal"], textColor=INK, fontSize=9.5, leading=14, spaceBefore=4, spaceAfter=14)
        story.append(Paragraph(rx_text, rx_style))
    else:
        story.append(Paragraph("No visits recorded yet for this patient.", styles["Normal"]))

    story.append(Spacer(1, 24))
    story.append(Paragraph(
        "<b>Important:</b> This report is generated by a research/hackathon prototype, not a "
        "diagnostic device. Parasitemia estimates and severity tiers are screening-level outputs "
        "from an AI classifier and have not been clinically validated. Trend labels (improving/"
        "worsening/stable) describe a numeric change between visits only -- they do not establish "
        "that a treatment is or isn't working, since parasitemia can vary for reasons unrelated to "
        "treatment (natural infection course, sampling variation, image quality). A confirmed "
        "diagnosis and treatment decisions should always come from a qualified clinician using "
        "validated diagnostic methods.",
        disclaimer_style,
    ))

    doc.build(story)
    return out_path


def generate_visit_report(visit: dict, out_path: str):
    """Generates a comprehensive PDF diagnostic report for a specific patient visit."""
    import base64
    doc = SimpleDocTemplate(out_path, pagesize=letter, topMargin=0.5 * inch, bottomMargin=0.5 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("TitleCustom", parent=styles["Title"], textColor=INK, fontSize=18, spaceAfter=4)
    sub_style = ParagraphStyle("SubCustom", parent=styles["Normal"], textColor=INK_SOFT, fontSize=9, spaceAfter=12)
    heading_style = ParagraphStyle("HeadingCustom", parent=styles["Heading2"], textColor=INK, fontSize=12, spaceBefore=12, spaceAfter=6)
    body_style = ParagraphStyle("BodyCustom", parent=styles["Normal"], textColor=INK, fontSize=9, leading=13)
    disclaimer_style = ParagraphStyle("Disclaimer", parent=styles["Normal"], textColor=INK_SOFT, fontSize=8, leading=11)

    story = []
    story.append(Paragraph("CELL SCOPE — AI CLINICAL DIAGNOSTIC REPORT", title_style))
    story.append(Paragraph("Automated Hematology & Malaria Explainability Analysis", sub_style))

    # Patient Metadata Table
    patient_name = visit.get("patient_name") or visit.get("name") or "Anonymous Patient"
    patient_code = visit.get("patient_code") or f"CS-{visit.get('patient_id', 1000)}"
    age = visit.get("age", 30)
    gender = visit.get("gender", "Male")
    phone = visit.get("phone", "N/A")
    visit_date = visit.get("visit_date", "2026-08-14")

    meta_data = [
        ["Patient Name:", patient_name, "Patient ID / MRN:", patient_code],
        ["Age / Gender:", f"{age} yrs / {gender}", "Contact Phone:", phone or "N/A"],
        ["Diagnostic Date:", visit_date, "Analysis Mode:", f"{visit.get('cells_analyzed', 1)} Cell(s) Evaluated"]
    ]
    meta_table = Table(meta_data, colWidths=[1.4 * inch, 2.1 * inch, 1.4 * inch, 2.1 * inch])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("TEXTCOLOR", (0, 0), (-1, -1), INK),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # Diagnostic Finding Banner
    result = visit.get("diagnosis_result", "Uninfected")
    confidence = visit.get("confidence_score", 95.0)
    risk_band = visit.get("risk_band", "Low risk")
    tagline = visit.get("risk_tagline", "Routine evaluation")
    is_positive = result in ["Parasitized", "Malaria Detected"] or visit.get("parasitemia_pct", 0) > 0

    verdict_bg = colors.HexColor("#FFF1F2") if is_positive else colors.HexColor("#F0FDF4")
    verdict_border = colors.HexColor("#E11D48") if is_positive else colors.HexColor("#10B981")
    verdict_text_color = colors.HexColor("#9F1239") if is_positive else colors.HexColor("#047857")

    verdict_content = [
        [
            Paragraph(f"<b>DIAGNOSTIC VERDICT:</b> {result.upper()} ({confidence:.1f}% Confidence)", ParagraphStyle("V1", parent=styles["Normal"], textColor=verdict_text_color, fontSize=12, fontName="Helvetica-Bold")),
            Paragraph(f"<b>RISK TIER:</b> {risk_band.upper()}", ParagraphStyle("V2", parent=styles["Normal"], textColor=verdict_text_color, fontSize=10, fontName="Helvetica-Bold", alignment=2))
        ],
        [
            Paragraph(f"<b>Clinical Advisory:</b> {tagline}", ParagraphStyle("V3", parent=styles["Normal"], textColor=INK, fontSize=9)),
            Paragraph(f"Parasitemia: {visit.get('parasitemia_pct', 0.0)}%", ParagraphStyle("V4", parent=styles["Normal"], textColor=INK_SOFT, fontSize=9, alignment=2))
        ]
    ]
    verdict_table = Table(verdict_content, colWidths=[4.5 * inch, 2.5 * inch])
    verdict_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), verdict_bg),
        ("BOX", (0, 0), (-1, -1), 1.5, verdict_border),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(verdict_table)
    story.append(Spacer(1, 10))

    # Microscopic & Grad-CAM Image Pair
    img_b64 = visit.get("image_data")
    heat_b64 = visit.get("heatmap_data")
    if img_b64 and heat_b64:
        try:
            raw_img_bytes = base64.b64decode(img_b64.split(",")[-1])
            raw_heat_bytes = base64.b64decode(heat_b64.split(",")[-1])

            img_obj = RLImage(io.BytesIO(raw_img_bytes), width=2.4 * inch, height=2.4 * inch)
            heat_obj = RLImage(io.BytesIO(raw_heat_bytes), width=2.4 * inch, height=2.4 * inch)

            img_table_data = [
                [Paragraph("<b>Original Blood Cell Smear</b>", body_style), Paragraph("<b>Grad-CAM Explainability Heatmap</b>", body_style)],
                [img_obj, heat_obj]
            ]
            img_table = Table(img_table_data, colWidths=[3.5 * inch, 3.5 * inch])
            img_table.setStyle(TableStyle([
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            story.append(img_table)
            story.append(Spacer(1, 8))
        except Exception:
            pass

    # Treatment & Prescription Guidelines
    story.append(Paragraph("Clinical Treatment & Prescribed Framework", heading_style))
    if is_positive:
        rx_html = (
            "• <b>First-Line Chemotherapy:</b> Artemether-Lumefantrine (Coartem 80/480mg) 6-dose oral course.<br/>"
            "• <b>Supportive Care:</b> Paracetamol 500mg as needed for pyrexia; aggressive oral/IV hydration.<br/>"
            "• <b>Follow-Up Protocol:</b> Repeat Giemsa thin/thick smear microscopy at 48-72 hours to verify clearance."
        )
    else:
        rx_html = (
            "• <b>Chemotherapy:</b> No antimalarial chemotherapy indicated at this time.<br/>"
            "• <b>Supportive Care:</b> Standard symptomatic care for febrile illness if symptoms persist.<br/>"
            "• <b>Follow-Up:</b> Re-screen if high fever or chills recur within 7-14 days."
        )
    story.append(Paragraph(rx_html, body_style))
    story.append(Spacer(1, 14))

    # Disclaimer
    story.append(Paragraph(
        "<b>Important Clinical Notice:</b> CellScope AI analysis is an automated screening tool intended for assistive triage "
        "and research support. Confirmation by certified clinical microscopy or rapid diagnostic test (RDT) is recommended prior to "
        "initiating clinical intervention.",
        disclaimer_style
    ))

    doc.build(story)
    return out_path
